name: CI/CD Pipeline
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Забираем код из репозитория
        uses: actions/checkout@v4

      - name: Сборка Docker и запуск Pytest
        run: |
          cd django_coworking
      
          touch .env
          echo "DB_NAME=postgres" >> .env
          echo "DB_USER=postgres" >> .env
          echo "DB_PASS=12345" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env
          echo "SECRET_KEY=super_secret_test_key" >> .env
          
          docker compose build
          
          docker compose up -d db
          sleep 5
          
          docker compose run --rm web pytest